src/routes/web.php
<?php

Route::group(['middleware' => ['web', 'auth']], function () {
    Route::prefix('familyportal')->group(function() {
        Route::get('/', 'Enssop\FamilyPortal\Http\Controllers\FamilyPortalController@index')->name('FamilyPortal');
        Route::resource('/user', 'Enssop\FamilyPortal\Http\Controllers\UserController');
        Route::resource('/person', 'Enssop\FamilyPortal\Http\Controllers\PersonController');
        Route::resource('/registration', 'Enssop\FamilyPortal\Http\Controllers\RegistrationController');
        Route::prefix('agent')->group(function() {
        Route::get('/', 'Enssop\FamilyPortal\Http\Controllers\AgentController@index')->name('Agent');
        Route::resource('/school', 'Enssop\FamilyPortal\Http\Controllers\SchoolController');
        });
        Route::fallback(function () {
            return redirect()->route('/home');
        });
    });
});

src/resources/views/agent.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    <h1 class="text-center">Tabeau de bord</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="card col-md-8">
                <div class="card-body text-center">
                    <h5 class="card-title">
                        MON ESPACE
                    </h5>
                    <p class="card-text d-inline-block text-left">
                        Agent {{ $user->name }}
                    </p>
                    <div class="card-footer">
                        <a href="{{ route('user.show', $user->id)}}">
                            <i class="fas fa-lock">
                                <p class="icon-profil">Identifiants</p>
                            </i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 m-auto">
            <div>
                <div class="card-deck">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-user fa-2x"></i></h5>
                            <p class="card-text">Ajouter une personne
                            </p>
                        </div>
                    </div>
                    <div class="card" onclick="window.location='{{ route('person.index') }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-users fa-2x"></i></h5>
                            <p class="card-text">Liste des personnes
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"></h5>
                            <p class="card-text"></p>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="card-deck">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-plus"></i><i
                                    class="fas fa-file-signature fa-2x"></i>
                            </h5>
                            <p class="card-text">Ajouter une inscription
                            </p>
                        </div>
                    </div>
                    <div class="card" onclick="window.location='{{ route('registration.index') }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-file-signature fa-2x"></i></h5>
                            <p class="card-text">Liste des inscriptions
                            </p>
                        </div>
                    </div>
                    <div class="card" onclick="window.location='{{ route('registration.index', ['status' =>  'attente']) }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="far fa-clock fa-2x"></i></h5>
                            <p class="card-text">Liste des inscriptions en attente
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="card-deck">
                    <div class="card" onclick="window.location='{{ route('school.index') }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-school fa-2x"></i></h5>
                            <p class="card-text">Liste des écoles
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/index.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container-fluid">
    @if (session('status'))
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i>close</i>
                </button>
                <span>{{ session('status') }}</span>
            </div>
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col-md-4">
            <div>
                <h2>MON ESPACE</h2>
                <div class="card col-md-8">
                    <img src="{{ asset($resp->civility->image_path) }}" class="card-img-top mx-auto avatar"
                        alt="{{ $resp->civility->image_path }}">
                    <div class="card-body text-center">
                        <h5 class="card-title">
                            {{ $resp->first_name }} <b>{{ $resp->last_name }}</b>
                        </h5>
                        <p class="card-text d-inline-block text-left">
                            {{ $resp->adress  }}<br>
                            {{ $resp->postalcode }} {{ $resp->city }}<br>
                            {{ $resp->phone }}<br>
                            {{ $resp->mobile_phone }}<br>
                            {{ $resp->email }}
                        </p>
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-6">
                                    <a href="{{ route('person.show', $resp) }}">
                                        <i class="fas fa-user-alt">
                                            <p class="icon-profil">Profil</p>
                                        </i>
                                    </a>
                                </div>
                                <div class="col-6">
                                    <a href="{{ route('user.show', $resp->user->id)}}">
                                        <i class="fas fa-lock">
                                            <p class="icon-profil">Identifiants</p>
                                        </i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h2>CO-REPRESENTANTS</h2>
                @if ($co_resp !== null)
                <div class="card col-md-6" onclick="window.location='{{ route('person.show', $co_resp) }}'">
                    <img src="{{ asset($co_resp->civility->image_path) }}" class="card-img-top mx-auto avatar"
                        alt="{{ $co_resp->civility->image_path }}">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                            {{ $co_resp->first_name }} <b>{{ $co_resp->last_name }}</b>
                        </h5>
                        <p class="card-text">

                        </p>
                    </div>
                </div>
                @endif
            </div>
            <div>
                <h2>MEMBRES FOYER</h2>
                <div class="card-deck">
                    @foreach ($children as $child)
                    <div class="card col-md-4" onclick="window.location='{{ route('person.show', $child) }}'">
                        <img src="{{ asset($child->civility->image_path) }}" class="card-img-top mx-auto avatar"
                            alt="{{ $child->civility->image_path }}">
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                {{ $child->first_name }}
                            </h5>
                            <p class="card-text">

                            </p>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
            <div>
                <h2>CONTACTS</h2>
                <div class="card-deck">
                    @foreach ($other_resps as $other_resp)
                    <div class="card col-md-4" onclick="window.location='{{ route('person.show', $other_resp) }}'">
                        <img src="{{ asset($other_resp->civility->image_path) }}" class="card-img-top mx-auto avatar"
                            alt="{{ $other_resp->civility->image_path }}">
                        <div class="card-body">
                            <h5 class="card-title text-center">
                                {{ $other_resp->first_name }} <b>{{ $other_resp->last_name }}</b>
                            </h5>
                            <p class="card-text text-center">

                            </p>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="col-md-8 m-auto">
            <div>
                <h2>MON TABLEAU DE BORD</h2>
                <div class="card-deck">
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="far fa-file-alt fa-2x"></i></h5>
                            <p class="card-text">
                                Dernières de demandes
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="far fa-envelope-open fa-2x"></i></h5>
                            <p class="card-text">
                                Echanges à lire
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-file-invoice-dollar fa-2x"></i></h5>
                            <p class="card-text">
                                Mes factures
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-file-archive fa-2x"></i></i></h5>
                            <p class="card-text">
                                Pièces justificatives
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-map-marker-alt fa-2x"></i></i></i></h5>
                            <p class="card-text">
                                Coordonnées
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h2>MA FAMILLE</h2>
                <div class="card-deck">
                    <div class="card" onclick="window.location='{{ route('registration.index') }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="far fa-clock fa-2x"></i></h5>
                            <p class="card-text">
                                Modifier/Annuler les...
                            </p>
                        </div>
                    </div>
                    <div class="card" onclick="window.location='{{ route('registration.create') }}'">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-file-signature fa-2x"></i></h5>
                            <p class="card-text">
                                Créer une inscription
                            </p>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body text-center">
                            <h5 class="card-title"><i class="fas fa-calculator fa-2x"></i></h5>
                            <p class="card-text">
                                Simulation des tarifs
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

src/resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- dataTables -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

    <title>{!! config('FamilyPortal.name') !!}</title>

    <!-- CSS File -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('enssop/FamilyPortal/css/FamilyPortal.css') }}">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <a class="navbar-brand" href="{{ route('FamilyPortal') }}">
                    {{ preg_replace('/(?=(?<!^)[[:upper:]])/', ' ', config('FamilyPortal.name', 'Portail Famille')) }}
                </a>
                @role('parent')
                <div class="dropdown">
                    <a class="navbar-brand" data-toggle="dropdown">Ajouter un menbre à la famille</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ route('person.create', ['person_role_id' => 1]) }}">Parent</a>
                        <a class="dropdown-item" href="{{ route('person.create', ['person_role_id' => 2]) }}">Enfant</a>
                        <a class="dropdown-item" href="{{ route('person.create', ['person_role_id' => 3]) }}">Contact</a>
                    </div>
                </div>
                @endrole
                <a class="navbar-brand" href="#">Actualités</a>
                <a class="navbar-brand" href="#">Activités</a>
                <a class="navbar-brand" href="#">Infos Pratiques</a>
                <a class="navbar-brand" href="#">Edition de documents</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                    style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main id="app" class="py-4">
            @yield('content')
        </main>
    </div>
    {{-- Laravel JS File --}}
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- dataTables -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" defer></script>

    {{-- dataTables config --}}
    <script src="{{ asset('enssop/FamilyPortal/js/FamilyPortal-Datatable.js') }}" defer></script>

    {{-- JS File --}}
    <script src="{{ asset('enssop/FamilyPortal/js/FamilyPortal.js') }}" defer></script>

</body>

</html>

src/resources/views/person/index.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
        <table class="datatable">
            <thead>
                <tr>
                    <th>Famille</th>
                    <th>Civilité</th>
                    <th>Role</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Né le</th>
                    <th>A</th>
                    <th>Situation</th>
                    <th>Adresse</th>
                    <th>Code postal</th>
                    <th>Ville</th>
                    <th>Téléphone Domicile</th>
                    <th>Portable</th>
                    <th>Email</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($people as $person)
                <tr>
                    <td>{{ $person->family->id }}</td>
                    <td>{{ $person->civility->title }}</td>
                    <td>{{ $person->role->title }}</td>
                    <td>{{ $person->last_name }}</td>
                    <td>{{ $person->first_name }}</td>
                    <td>{{ $person->birthdate }}</td>
                    <td>{{ $person->birthplace }}</td>
                    @if ($person->situation_id == null)
                    <td></td>
                    @else
                    <td>{{ $person->situation->title }}</td>
                    @endif
                    <td>{{ $person->adress }}</td>
                    <td>{{ $person->postalcode }}</td>
                    <td>{{ $person->city }}</td>
                    <td>{{ $person->phone }}</td>
                    <td>{{ $person->mobile_phone }}</td>
                    <td>{{ $person->email }}</td>
                    <td>
                        <form class="d-flex justify-content-center" action="{{ route('person.show', $person) }}"
                            method="POST">
                            @csrf
                            @method('GET')
                            <button type="submit" class="btn btn-info"><i class="far fa-eye"></i></button>
                        </form>
                    </td>
                    <td>
                        <form class="d-flex justify-content-center" action="{{ route('person.edit', $person) }}"
                            method="POST">
                            @csrf
                            @method('GET')
                            <button type="submit" class="btn btn-warning"><i class="far fa-edit"></i></button>
                        </form>
                    </td>
                    <td>
                        <form class="d-flex justify-content-center" action="{{ route('person.destroy', $person) }}"
                            method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="fas fa-times"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

src/resources/views/schools/create.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    <form class="my-5" action="{{ route('school.store') }}" method="POST">
        @csrf
        @method('POST')
        <div class="card">
            <div class="card-header bg-primary">
                <h4 class="card-title">
                    Ajouter une école
                </h4>
            </div>
            <div class="card-body">
                <div class="form-group row">
                    <label for="school_title" class="col-2 col-form-label">Nom : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_title" name="title">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="school_code" class="col-2 col-form-label">Numéro : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_code" name="school_code">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="school_address" class="col-2 col-form-label">Adresse : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_address" name="address">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="school_city" class="col-2 col-form-label">Ville : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_city" name="city">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="school_postal_code" class="col-2 col-form-label">Code Postal : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_postal_code" name="postal_code">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="school_phone" class="col-2 col-form-label">Téléphone : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="school_phone" name="phone">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="www_addresse" class="col-2 col-form-label">Site web : </label>
                    <div class="col-10">
                        <input class="form-control" type="text" id="www_address" name="www_address">
                    </div>
                </div>
            </div>
            <div class="my-3 mx-auto">
                <button type="submit" class="btn btn-primary">Enregistrer</button>
            </div>
        </div>
    </form>
</div>
@endsection

src/resources/views/schools/index.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title">
                Liste des écoles
            </h4>
            <p class="card-category">
                <div class="text-right">
                    <a href="{{ route('school.create') }}" class="btn btn-sm btn-secondary">Ajouter une école</a>
                </div>
            </p>
        </div>
        <div class="card-body">
            @if (session('status'))
            <div class="row">
                <div class="col-sm-12">
                    <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                        <span>{{ session('status') }}</span>
                    </div>
                </div>
            </div>
            @endif
            <table class="datatable">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Numéro</th>
                        <th>Adresse</th>
                        <th>Ville</th>
                        <th>Code Postal</th>
                        <th>Téléphone</th>
                        <th>Site</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($schools as $school)
                    <tr>
                        <td>{{ $school->title }}</td>
                        <td>{{ $school->school_code }}</td>
                        <td>{{ $school->address }}</td>
                        <td>{{ $school->city }}</td>
                        <td>{{ $school->postal_code }}</td>
                        <td>{{ $school->phone }}</td>
                        <td>{{ $school->www_address }}</td>
                        <td>
                            <form class="d-flex justify-content-center" action="{{ route('school.show', $school) }}"
                                method="POST">
                                @csrf
                                @method('GET')
                                <button type="submit" class="btn btn-info"><i class="far fa-eye"></i></button>
                            </form>
                        </td>
                        <td>
                            <form class="d-flex justify-content-center" action="{{ route('school.edit', $school) }}"
                                method="POST">
                                @csrf
                                @method('GET')
                                <button type="submit" class="btn btn-warning"><i class="far fa-edit"></i></button>
                            </form>
                        </td>
                        <td>
                            <form class="d-flex justify-content-center" action="{{ route('school.destroy', $school) }}"
                                method="POST">
                                @csrf
                                @method('DELETE')
                                <button onclick="return confirm('Êtes-vous sûr de vouloir supprimer l\'école ?')"
                                    type="submit" class="btn btn-danger"><i class="fas fa-times"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

src/resources/views/users/edit.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    
</div>
@endsection

src/resources/views/users/index.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    
</div>
@endsection

src/resources/views/users/show.blade.php
@extends('FamilyPortal::layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">Identifiant utilisateur</div>
                <div class="card-body">
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label text-md-right">Nom</label>
                        <div class="col-md-6">
                            <input class="form-control" value="{{ $user->name }}" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label text-md-right">Adresse mail</label>

                        <div class="col-md-6">
                            <input class="form-control" value="{{$user->email }}" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-4 col-form-label text-md-right">Mot de Passe</label>

                        <div class="col-md-6">
                            <input type="password" class="form-control" value="{{ $user->password }}" disabled>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection